print("Hello and welcome to this daily challenge!")
name = input("now tell me your name: ")
print(f"thank you {name}")
age = input("now, tell me about your age! how old are you? ")
age = int(age)
print(f"that's great {name}. You have {age} years old. ")
print("Did you know this:")
print("The type of your name is: ", type(name), "& your entered age is: ", type(age), "?") 